name: CodeStyle C#

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build and check style
      run: |
        dotnet build
        dotnet format --check
